/**
 * Generates the inline icon registry from lucide-vue-next.
 *
 * simple-ui ships no icon dependency: components take `name` strings, and this
 * script inlines the required shapes into a committed source file. lucide is a
 * devDependency used only here.
 *
 * Icons are ISC licensed — see src/icons/NOTICE.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { icons } from 'lucide-vue-next'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** App-facing names → lucide icon names. */
const MAP = {
    // Spec §2.1 — required names
    refresh: 'RefreshCw',
    refreshright: 'RotateCw',
    plus: 'Plus',
    operation: 'Settings2',
    edit: 'Pencil',
    download: 'Download',
    view: 'Eye',
    tickets: 'Ticket',
    promotion: 'Send',
    document: 'FileText',
    select: 'Check',
    check: 'Check',
    morefilled: 'Ellipsis',
    delete: 'Trash2',
    close: 'X',
    arrowright: 'ArrowRight',
    arrowleft: 'ArrowLeft',
    arrowup: 'ArrowUp',
    arrowdown: 'ArrowDown',
    user: 'User',
    users: 'Users',
    copydocument: 'Copy',
    officebuilding: 'Building2',
    location: 'MapPin',
    setting: 'Settings',
    dataanalysis: 'ChartColumn',
    chevrondown: 'ChevronDown',
    chevronup: 'ChevronUp',
    chevronleft: 'ChevronLeft',
    chevronright: 'ChevronRight',
    upload: 'Upload',
    switchbutton: 'ToggleLeft',
    star: 'Star',
    odometer: 'Gauge',
    notebook: 'Notebook',
    money: 'Banknote',
    message: 'MessageSquare',
    medal: 'Medal',
    loading: 'LoaderCircle',
    key: 'KeyRound',
    fold: 'PanelLeftClose',
    cpu: 'Cpu',
    coin: 'Coins',
    calendar: 'Calendar',
    mail: 'Mail',
    phone: 'Phone',
    shieldcheck: 'ShieldCheck',
    image: 'Image',
    forbidden: 'Ban',
    maintenance: 'Wrench',
    // Library-internal + commonly needed by the components themselves
    search: 'Search',
    menu: 'Menu',
    sun: 'Sun',
    moon: 'Moon',
    github: 'Github',
    logout: 'LogOut',
    list: 'List',
    table: 'Table2',
    file: 'File',
    folder: 'Folder',
    bell: 'Bell',
    info: 'Info',
    alerttriangle: 'TriangleAlert',
    alertcircle: 'CircleAlert',
    checkcircle: 'CircleCheck',
    xcircle: 'CircleX',
    eyeoff: 'EyeOff',
    minus: 'Minus',
    play: 'Play',
    external: 'ExternalLink',
    filter: 'Funnel',
    sort: 'ArrowUpDown',
    lock: 'Lock',
    unlock: 'LockOpen',
    spinner: 'Loader',
    grid: 'LayoutGrid',
    columns: 'Columns3',
}

const SHAPE_TAGS = new Set(['path', 'circle', 'rect', 'line', 'polyline', 'polygon', 'ellipse'])
const ATTRS = new Set(['d', 'cx', 'cy', 'r', 'x', 'y', 'x1', 'x2', 'y1', 'y2', 'points', 'rx', 'ry', 'width', 'height'])

/**
 * lucide renders an <svg> whose `iconNode` prop holds the raw
 * `[tag, attrs][]` shape data — the cleanest thing to inline.
 */
function extract(iconFn) {
    const vnode = iconFn({}, { slots: {}, attrs: {} })
    const iconNode = vnode?.props?.iconNode
    if (!Array.isArray(iconNode)) {
        return []
    }
    return iconNode
        .filter(([tag]) => typeof tag === 'string' && SHAPE_TAGS.has(tag))
        .map(([tag, attrs]) => {
            const clean = {}
            for (const [key, value] of Object.entries(attrs ?? {})) {
                if (ATTRS.has(key) && value !== undefined && value !== null) {
                    clean[key] = String(value)
                }
            }
            return [tag, clean]
        })
}

const entries = {}
const missing = []

for (const [name, lucideName] of Object.entries(MAP)) {
    const iconFn = icons[lucideName]
    if (!iconFn) {
        missing.push(`${name} → ${lucideName}`)
        continue
    }
    const shapes = extract(iconFn)
    if (!shapes.length) {
        missing.push(`${name} → ${lucideName} (no shapes)`)
        continue
    }
    entries[name] = shapes
}

if (missing.length) {
    console.error('[icons] unresolved names:\n  ' + missing.join('\n  '))
    process.exit(1)
}

const names = Object.keys(entries).sort()
const body = names
    .map((name) => `    ${JSON.stringify(name)}: ${JSON.stringify(entries[name])},`)
    .join('\n')

const output = `/**
 * Inline icon registry — generated by scripts/build-icons.mjs.
 *
 * Do not edit by hand: run \`node scripts/build-icons.mjs\` after changing the
 * name map. Shapes come from lucide (ISC licensed) — see ./NOTICE.
 *
 * ${names.length} icons. Keys are lowercase, so lookups are case-insensitive.
 */
export type IconShape = [string, Record<string, string>]

export const ICON_VIEW_BOX = '0 0 24 24'

export const icons: Record<string, IconShape[]> = {
${body}
}

/** All registered names, useful for tooling and docs. */
export const iconNames: string[] = ${JSON.stringify(names)}
`

mkdirSync(join(root, 'src', 'icons'), { recursive: true })
writeFileSync(join(root, 'src', 'icons', 'registry.ts'), output)
console.log(`[icons] ${names.length} icons → src/icons/registry.ts`)
